spring:
  application:
    name: wallet-api
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

coincap-config:
  base-url: https://api.coincap.io/v2
  timeout: 5000