spring:
  application:
    name: wallet-api
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  docker:
    compose:
      enabled: true
      stop:
        command: down

coincap-config:
  base-url: https://api.coincap.io/v2
  timeout: 5000